name: Sync Gist with Repo

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes (you can change the frequency)
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  sync-gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Clone Gist
      run: |
        git clone https://gist.github.com/01f359244d679c576502fe2a65819014.git gist-repo
        cd gist-repo
        cp -r . ../
        cd ..

    - name: Commit Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Sync Gist with repository" || echo "No changes detected"

    - name: Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git remote set-url origin https://shubhamcoder260:${{ secrets.GH_PAT }}@github.com/<your-username>/my-notebooks-repo.git
        git push origin main
